-- Add stock_quantity column to menu_items
ALTER TABLE public.menu_items ADD COLUMN stock_quantity integer DEFAULT null;

-- Insert all menu items from the static menu
INSERT INTO public.menu_items (name, price, description, category, is_available, stock_quantity) VALUES
-- Cachaças e Aguardentes
('Artesanais: Branca, Carvalho, Côco, Banana, Pequi, Mel c/ Gengibre, Carqueijo, Caju', 6.00, NULL, 'cachacas', true, NULL),
('Cabaré', 6.00, NULL, 'cachacas', true, NULL),
('Cachaça 51', 5.00, NULL, 'cachacas', true, NULL),
('Canelinha', 5.00, NULL, 'cachacas', true, NULL),
('Catuaba', 6.00, NULL, 'cachacas', true, NULL),
('Contine', 6.00, NULL, 'cachacas', true, NULL),
('Domecq', 10.00, NULL, 'cachacas', true, NULL),
('Montilla Cristal', 8.00, NULL, 'cachacas', true, NULL),
('Montilla Ouro', 8.00, NULL, 'cachacas', true, NULL),
('Paratudo', 5.00, NULL, 'cachacas', true, NULL),
('Pitu', 5.00, NULL, 'cachacas', true, NULL),
('Sagatiba', 5.00, NULL, 'cachacas', true, NULL),
('Salinas', 12.00, NULL, 'cachacas', true, NULL),
('São Francisco', 6.00, NULL, 'cachacas', true, NULL),
('Seleta', 6.00, NULL, 'cachacas', true, NULL),
('Velho Barreiro', 8.00, NULL, 'cachacas', true, NULL),
-- Licores e Destilados
('Campari', 12.00, NULL, 'licores', true, NULL),
('Cynar', 10.00, NULL, 'licores', true, NULL),
('Dom Luiz', 10.00, NULL, 'licores', true, NULL),
('Dreher', 6.00, NULL, 'licores', true, NULL),
('Gin', 6.00, NULL, 'licores', true, NULL),
('Gin Abacaxi', 6.00, NULL, 'licores', true, NULL),
('Gin Maçã Verde', 6.00, NULL, 'licores', true, NULL),
('Jurupinga', 12.00, NULL, 'licores', true, NULL),
('Licor 43', 12.00, NULL, 'licores', true, NULL),
('Matuta Banana', 12.00, NULL, 'licores', true, NULL),
('Menta', 6.00, NULL, 'licores', true, NULL),
('St Remy', 12.00, NULL, 'licores', true, NULL),
('Tequila Jose Cuervo Ouro', 18.00, NULL, 'licores', true, NULL),
('Xiboquinha', 6.00, NULL, 'licores', true, NULL),
('Ypioca Carvalho', 10.00, NULL, 'licores', true, NULL),
('Ypioca Ouro', 5.00, NULL, 'licores', true, NULL),
-- Whiskies
('Whisky Ballantines', 20.00, NULL, 'whiskies', true, NULL),
('Whisky Chivas 12 anos', 27.00, NULL, 'whiskies', true, NULL),
('Whisky Old Eight', 12.00, NULL, 'whiskies', true, NULL),
('Whisky Passport', 15.00, NULL, 'whiskies', true, NULL),
('Whisky Passport Honey', 13.00, NULL, 'whiskies', true, NULL),
('Whisky Passport Selection', 20.00, NULL, 'whiskies', true, NULL),
('Whisky Red Label', 12.00, NULL, 'whiskies', true, NULL),
('Whisky White Horse', 12.00, NULL, 'whiskies', true, NULL),
-- Vodka
('Vodka Smirnoff', 20.00, NULL, 'vodka', true, NULL),
-- Cervejas Garrafa 600ml
('Amstel 600ml', 12.00, NULL, 'cervejas-garrafa', true, NULL),
('Skol 600ml', 12.00, NULL, 'cervejas-garrafa', true, NULL),
('Original 600ml', 12.00, NULL, 'cervejas-garrafa', true, NULL),
('Heineken 600ml', 18.00, NULL, 'cervejas-garrafa', true, NULL),
-- Cervejas Lata e Long Neck
('Skol 1L (Litrão)', 15.00, NULL, 'cervejas-lata', true, NULL),
('Corona Extra 330ml', 11.00, NULL, 'cervejas-lata', true, NULL),
('Império 269ml', 5.00, NULL, 'cervejas-lata', true, NULL),
('Budweiser 269ml', 6.00, NULL, 'cervejas-lata', true, NULL),
('Amstel 269ml', 6.00, NULL, 'cervejas-lata', true, NULL),
('Skol Pilsen 269ml', 6.00, NULL, 'cervejas-lata', true, NULL),
('Brahma Duplo Malte 350ml', 7.50, NULL, 'cervejas-lata', true, NULL),
-- Cervejas Zero Álcool
('Itapaiva Zero 350ml', 6.00, NULL, 'cervejas-zero', true, NULL),
('Heineken Zero 350ml', 7.00, NULL, 'cervejas-zero', true, NULL),
('Sol Zero', 12.00, NULL, 'cervejas-zero', true, NULL),
-- Refrigerantes Lata
('Itubaina 350ml', 5.00, NULL, 'refrigerantes-lata', true, NULL),
('Coca-Cola 350ml', 6.00, NULL, 'refrigerantes-lata', true, NULL),
('Guaraná Antarctica 350ml', 6.00, NULL, 'refrigerantes-lata', true, NULL),
('Pepsi Cola 350ml', 6.00, NULL, 'refrigerantes-lata', true, NULL),
('Sprite 350ml', 6.00, NULL, 'refrigerantes-lata', true, NULL),
('Fanta Laranja 350ml', 6.00, NULL, 'refrigerantes-lata', true, NULL),
('Coca-Cola Sem Açúcar 310ml', 6.00, NULL, 'refrigerantes-lata', true, NULL),
-- Refrigerantes Garrafa 2L
('Guaraná Antarctica 2L', 14.00, NULL, 'refrigerantes-garrafa', true, NULL),
('Soda 2L', 14.00, NULL, 'refrigerantes-garrafa', true, NULL),
('Sukita Laranja 2L', 14.00, NULL, 'refrigerantes-garrafa', true, NULL),
('Sprite 2L', 14.00, NULL, 'refrigerantes-garrafa', true, NULL),
('Fanta Laranja 2L', 14.00, NULL, 'refrigerantes-garrafa', true, NULL),
('Fanta Uva 2L', 14.00, NULL, 'refrigerantes-garrafa', true, NULL),
('Coca-Cola 2L', 18.00, NULL, 'refrigerantes-garrafa', true, NULL),
-- Caipirinhas Limão
('Caipirinha Limão Velho Barreiro', 18.00, NULL, 'caipirinhas-limao', true, NULL),
('Caipirinha Limão Vodka', 25.00, NULL, 'caipirinhas-limao', true, NULL),
-- Caipirinhas Cambuci
('Caipirinha Cambuci Velho Barreiro', 20.00, NULL, 'caipirinhas-cambuci', true, NULL),
('Caipirinha Cambuci Vodka', 26.00, NULL, 'caipirinhas-cambuci', true, NULL),
-- Caipirinhas Shangri-La
('Caipirinha Shangri-La Velho Barreiro', 20.00, NULL, 'caipirinhas-shangrila', true, NULL),
('Caipirinha Shangri-La Vodka', 25.00, NULL, 'caipirinhas-shangrila', true, NULL),
-- Drinks Especiais
('Shangri-La s/ álcool (suco de cambuci c/ groselha)', 15.00, NULL, 'drinks', true, NULL),
('Vinho Tinto São Tomé', 8.00, NULL, 'drinks', true, NULL),
('Vinho Branco Seco Campo Largo', 8.00, NULL, 'drinks', true, NULL),
('Campari c/ Laranja', 17.00, NULL, 'drinks', true, NULL),
-- Bebidas Mistas
('Skol Beats Senses 269ml', 8.00, NULL, 'bebidas-mistas', true, NULL),
('Chopp de Vinho Draft', 18.00, NULL, 'bebidas-mistas', true, NULL),
('Red Line 600ml', 18.00, NULL, 'bebidas-mistas', true, NULL),
-- Energéticos
('Red Bull 250ml', 14.00, NULL, 'energeticos', true, NULL),
('Baly 473ml', 12.00, NULL, 'energeticos', true, NULL),
('TNT 473ml', 12.00, NULL, 'energeticos', true, NULL),
('Monster 473ml', 14.00, NULL, 'energeticos', true, NULL),
('Vibe 2L', 25.00, NULL, 'energeticos', true, NULL),
('Baly 2L', 25.00, NULL, 'energeticos', true, NULL),
-- Águas e Hidratação
('Água Tônica Antarctica 350ml', 7.00, NULL, 'aguas', true, NULL),
('Água com gás 510ml', 4.50, NULL, 'aguas', true, NULL),
('Água sem gás 510ml', 3.00, NULL, 'aguas', true, NULL),
('Água sem gás 1,5L', 8.00, NULL, 'aguas', true, NULL),
('Água de Coco Natural', 10.00, NULL, 'aguas', true, NULL),
-- Sucos e Diversos
('Gatorade 500ml', 9.00, NULL, 'sucos', true, NULL),
('Suco Del Valle 290ml', 7.00, NULL, 'sucos', true, NULL),
('Suco Laranja 1L', 12.00, NULL, 'sucos', true, NULL),
('Gelo Saborizado', 6.00, NULL, 'sucos', true, NULL),
('Guaraviton', 4.00, NULL, 'sucos', true, NULL),
-- Porções
('Frango à Passarinho - Pequena', 30.00, 'Porção Pequena', 'porcoes', true, NULL),
('Frango à Passarinho - Grande', 50.00, 'Porção Grande', 'porcoes', true, NULL),
('Calabresa Acebolada c/ Pão - Pequena', 30.00, 'Porção Pequena', 'porcoes', true, NULL),
('Calabresa Acebolada c/ Pão - Grande', 50.00, 'Porção Grande', 'porcoes', true, NULL),
('Batata Frita 300g', 25.00, '300g', 'porcoes', true, NULL),
('Batata Frita 500g', 40.00, '500g', 'porcoes', true, NULL),
('Salame 100g', 20.00, '100g', 'porcoes', true, NULL),
('Salame 200g', 35.00, '200g', 'porcoes', true, NULL),
('Azeitona Verde', 15.00, NULL, 'porcoes', true, NULL),
('Nuggets 6 unid', 11.00, '6 unidades', 'porcoes', true, NULL),
('Nuggets 12 unid', 20.00, '12 unidades', 'porcoes', true, NULL),
-- Lanches Tradicionais
('Hambúrguer Tradicional', 12.00, 'Hambúrguer 55g', 'lanches-tradicionais', true, NULL),
('X Burguer Tradicional', 14.00, 'Hambúrguer 55g', 'lanches-tradicionais', true, NULL),
('X Bacon Tradicional', 19.00, 'Hambúrguer 55g', 'lanches-tradicionais', true, NULL),
('X Salada Tradicional', 16.00, 'Hambúrguer 55g', 'lanches-tradicionais', true, NULL),
('X Calabresa Tradicional', 19.00, 'Hambúrguer 55g', 'lanches-tradicionais', true, NULL),
('X Shangri-La', 18.00, 'Pão de forma, ovo, bacon e queijo', 'lanches-tradicionais', true, NULL),
-- Lanches Gourmet
('Hambúrguer Gourmet', 17.00, 'Hambúrguer 150g - Acompanha batata frita', 'lanches-gourmet', true, NULL),
('X Burguer Gourmet', 21.00, 'Hambúrguer 150g - Acompanha batata frita', 'lanches-gourmet', true, NULL),
('X Bacon Gourmet', 26.00, 'Hambúrguer 150g - Acompanha batata frita', 'lanches-gourmet', true, NULL),
('X Salada Gourmet', 23.00, 'Hambúrguer 150g - Acompanha batata frita', 'lanches-gourmet', true, NULL),
-- Baldes Promocionais
('Balde Cerveja', 40.00, '08 unidades – Latas 269ml (Império, Amstel, Budweiser etc.)', 'baldes', true, NULL),
('Balde Whisky', 180.00, '1 Whisky Red Label + 4 unidades de gelo + 1 energético (Baly ou Vibe)', 'baldes', true, NULL),
-- Churrasqueira
('Gelo 5kg', 12.00, NULL, 'churrasqueira', true, NULL),
('Carvão 2kg', 15.00, NULL, 'churrasqueira', true, NULL);